app = "emailback"
primary_region = "gru"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[processes]
  app = "node server.js"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
